# Generated by Django 5.0.6 on 2024-05-24 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projectillo', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='customuser',
        ),
    ]
