# Generated by Django 5.0.6 on 2024-05-27 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectillo', '0005_tasks_projects_deadline_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='projectillo.profile'),
        ),
    ]
