# Generated by Django 5.0.6 on 2024-05-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectillo', '0007_tasks_status_alter_projects_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='done',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Complete')], default='', max_length=3),
        ),
    ]
