# Generated by Django 5.0.6 on 2024-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectillo', '0008_remove_tasks_done_alter_tasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='text',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='Task_Name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='deadline',
        ),
        migrations.AddField(
            model_name='projects',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='', max_length=12),
        ),
    ]
