# Generated by Django 5.0.6 on 2024-05-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectillo', '0009_rename_text_tasks_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='due_date',
        ),
        migrations.AddField(
            model_name='projects',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
